App:
  name: cortexjs-www

Server:
  cluster: false
  port: 8080
  secret: "cortexjs-www-session"
  pretty: true

Logger:
  level: warn
  stdout: true

Auth:
  clientID: "b058836b6bdd02928e98"
  clientSecret: "28a4fe357cc57db6209a8eb3f315488472649633"
  callbackUrl: "http://localhost:8010/auth/github/callback"

Couch:
  address: "http://localhost:15984"
  rewrite: "/registry/_design/app/_rewrite"
Error:
  showStack: true